---
title: "Environment"
author: "Pranav Gupta"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```


```{r}
library(sf)
library(tidyverse)
library(cowplot)
library(patchwork)
library(lfe)
library(expss)
library(lubridate)
library(zoo)
library(ggthemes)
```

```{r}
#user <- "agnihotri"
#user <- "anust"
user <- "prana"
```

```{r}
ec<-readRDS(paste0("C:/Users/",user,"/Dropbox/agnihotri_gupta/Environment_Clearance/EC_All_States.rds"))

ec$submit_year<-format(as.Date(ec$submit_date, format="%d/%m/%Y"),"%Y")
```


## Build
```{r}
grant_ec <- ec %>% filter(Status %in% c("EC Granted","EC Granted - Processed offline")) %>% distinct()
```

```{r}
grant_ec$duplicate <- duplicated(grant_ec$Proposal)
table(grant_ec$duplicate)
```
##Simplify the Categories of Projects 

```{r}

table(grant_ec$Category_Simplified)

```





```{r}
summary(grant_ec$time)

#Exclude if length  less than 0

grant_ec <- grant_ec %>% filter(time >=0) #Some obs have negative grant time
```


```{r extract-year}
#Year of Submission
#grant_ec$submit_year<-(gsub('^([0-9][0-9][0-9][0-9]).*','\\1',grant_ec$submit))
grant_ec$submit_year <- year(grant_ec$submit)
grant_ec$grant_year <- year(grant_ec$grant)

#Year-Month of Submission
grant_ec$submit_year_mon<-as.yearmon(grant_ec$submit)
```


```{r}
density_year <- ggplot(grant_ec, aes(x = submit_year)) +
  geom_bar() +
  theme_minimal()  + ggtitle('EC Granted by Year') + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))


print(density_year)
```

## Descriptives

```{r}
density_year_non_coal_mining <- ggplot(filter(grant_ec,Category=='Non-Coal Mining'), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
  theme_minimal() + facet_wrap(~state1) + ggtitle('Non Coal Mining Projects (EC)') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

print(density_year_non_coal_mining)
```

```{r}
density_year_infra <- ggplot(filter(grant_ec,grepl('INFRA',Category)), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
  theme_minimal() + facet_wrap(~state1) + ggtitle('INFRA Projects') 

print(density_year_infra)
```


```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(ec,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

#ggsave(paste0("C:/Users/",user,"/Dropbox/Apps/Overleaf/MPSA_2024/Figures/applications_submitted.eps"))

```
```{r}
density_time <- ggplot(grant_ec, aes(x = time)) +
  geom_density(fill = "skyblue", color = "darkblue", alpha = 0.5) +
  theme_minimal()

print(density_time)
```

```{r}
ggplot(grant_ec, aes(x = Category_Simplified)) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "skyblue", color = "darkblue") +
  labs(x = "Category", y = "Percentage", title = "Category - EC granted") +
  theme_economist() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggsave(paste0("C:/Users/",user,"/Dropbox/Apps/Overleaf/MPSA_2024/Figures/applications_category_wise.eps"))

```

```{r}
ggplot(grant_ec, aes(x = Category_Simplified, y = time)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", outlier.shape = NA) +
  labs(x = "Group", y = "Value", title = "Box Plot") +
  theme_minimal() + scale_y_log10() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
type <- grant_ec %>% group_by(Category_Simplified,state1) %>% summarise(avg = mean(time),sd = sd(time), count = n())
type$cd <- type$sd/type$avg
```
```{r}
infra_time <- type %>% ggplot(aes(x =state1, y = avg)) +  geom_bar(stat = "identity", fill = "steelblue") +
  theme(axis.text.x = element_text(angle = 180, vjust = 0.5, hjust = 1))+
  facet_wrap(~Category_Simplified)+
  labs(x = "State", y = "Avg time",title = "Average time for projects") +theme_minimal()+
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
print(infra_time)
```

```{r}
infra_time <- type %>% filter(Category_Simplified=="Infrastructure") %>% ggplot(aes(x =state1, y = avg)) +  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "State", y = "Avg time",title = "Average time for Infra projects") +
  theme_minimal() +theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))

print(infra_time)
```



```{r}
mining_time <- type %>% filter(Category_Simplified=="Non-Coal Mining") %>% ggplot(aes(x =state1, y = avg)) +  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "State", y = "Avg time",title = "Avg - Non coal mining") +
  theme_minimal() + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))

print(mining_time)
```

```{r}
ind_time <- type %>% filter(Category_Simplified=="Industrial") %>% ggplot(aes(x =state1, y = avg)) +  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "State", y = "Avg time",title = "Avg - Industrial") +
  theme_minimal()

print(ind_time) + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))
```

# State Scatter

```{r}
state_ind <- ec %>% filter(year %in% c(2018:2023) & Category_Simplified == "Industrial") %>% group_by(state1) %>% summarise(count=n(),time=mean(time2,na.rm=T)) %>% rename(state=state1)


state_inf <- ec %>% filter(year %in% c(2018:2023) & Category_Simplified != "Infrastructure") %>% group_by(state1) %>% summarise(count=n(),time=mean(time2,na.rm=T)) %>% rename(state=state1)


state_mine <- ec %>% filter(year %in% c(2018:2023) & Category_Simplified != "Non-Coal Mining") %>% group_by(state1) %>% summarise(count=n(),time=mean(time2,na.rm=T)) %>% rename(state=state1)

```

```{r}
library(ggrepel)

ggplot(state_ind, aes(x = count, y = time, label = substr(state, 1, 3))) +  # Map aesthetics
  geom_point(color="red") +                                    # Add scatter points
geom_label_repel(max.overlaps = Inf,size=2) + 
  geom_hline(yintercept = median(state_ind$time), linetype = "dashed", color = "black") +  # Add horizontal line at Y median
  geom_vline(xintercept = median(state_ind$count), linetype = "dashed", color = "black") +  # Add vertical line at X median
# Add labels with a slight nudge
  theme_minimal() +                                 # Use a minimal theme
  labs(x = "Applications", y = "Time",title = "Industrial")  # Add labels and title

ggsave("C:/Users/prana/Desktop/ind.png")

```

```{r}
ggplot(state_inf, aes(x = count, y = time, label = substr(state, 1, 3))) +  # Map aesthetics
  geom_point(color="red") +                                    # Add scatter points
geom_label_repel(max.overlaps = Inf,size=2) + 
  geom_hline(yintercept = median(state_inf$time), linetype = "dashed", color = "black") +  # Add horizontal line at Y median
  geom_vline(xintercept = median(state_inf$count), linetype = "dashed", color = "black") +  # Add vertical line at X median
# Add labels with a slight nudge
  theme_minimal() +                                 # Use a minimal theme
  labs(x = "Applications", y = "Time",title = "Infrastructure")  # Add labels and title

ggsave("C:/Users/prana/Desktop/inf.png")

```


```{r}
ggplot(state_mine, aes(x = count, y = time, label = substr(state, 1, 3))) +  # Map aesthetics
  geom_point(color="red") +                                    # Add scatter points
geom_label_repel(max.overlaps = Inf,size=2) + 
  geom_hline(yintercept = median(state_mine$time), linetype = "dashed", color = "black") +  # Add horizontal line at Y median
  geom_vline(xintercept = median(state_mine$count), linetype = "dashed", color = "black") +  # Add vertical line at X median
# Add labels with a slight nudge
  theme_minimal() +                                 # Use a minimal theme
  labs(x = "Applications", y = "Time",title = "Non-Coal Mining")  # Add labels and title

ggsave("C:/Users/prana/Desktop/mine.png")
```


```{r}
table(ec$state1)
```
# Andhra Pradesh

```{r}
state_all <- ec %>% filter(state1=="Andhra_Pradesh")

grant_state <- grant_ec %>% filter(state1=="Andhra_Pradesh")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Bihar

```{r}
state_all <- ec %>% filter(state1=="Bihar")

grant_state <- grant_ec %>% filter(state1=="Bihar")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Chattisgarh

```{r}
state_all <- ec %>% filter(state1=="Chattisgarh")

grant_state <- grant_ec %>% filter(state1=="Chattisgarh")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Gujarat

```{r}
state_all <- ec %>% filter(state1=="Gujarat")

grant_state <- grant_ec %>% filter(state1=="Gujarat")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Haryana

```{r}
state_all <- ec %>% filter(state1=="Haryana")

grant_state <- grant_ec %>% filter(state1=="Haryana")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Himachal_Pradesh

```{r}
state_all <- ec %>% filter(state1=="Himachal_Pradesh")

grant_state <- grant_ec %>% filter(state1=="Himachal_Pradesh")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Jharkhand

```{r}
state_all <- ec %>% filter(state1=="Jharkhand")

grant_state <- grant_ec %>% filter(state1=="Jharkhand")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Kerala

```{r}
state_all <- ec %>% filter(state1=="Kerala")

grant_state <- grant_ec %>% filter(state1=="Kerala")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Karnataka

```{r}
state_all <- ec %>% filter(state1=="Karnataka")

grant_state <- grant_ec %>% filter(state1=="Karnataka")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Madhya_Pradesh

```{r}
state_all <- ec %>% filter(state1=="Madhya_Pradesh")

grant_state <- grant_ec %>% filter(state1=="Madhya_Pradesh")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Maharashtra

```{r}
state_all <- ec %>% filter(state1=="Maharashtra")

grant_state <- grant_ec %>% filter(state1=="Maharashtra")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Odisha

```{r}
state_all <- ec %>% filter(state1=="Odisha")

grant_state <- grant_ec %>% filter(state1=="Odisha")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Punjab

```{r}
state_all <- ec %>% filter(state1=="Punjab")

grant_state <- grant_ec %>% filter(state1=="Punjab")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Rajasthan

```{r}
state_all <- ec %>% filter(state1=="Rajasthan")

grant_state <- grant_ec %>% filter(state1=="Rajasthan")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Tamil_Nadu

```{r}
state_all <- ec %>% filter(state1=="Tamil_Nadu")

grant_state <- grant_ec %>% filter(state1=="Tamil_Nadu")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

# Telangana

```{r}
state_all <- ec %>% filter(state1=="Telangana")

grant_state <- grant_ec %>% filter(state1=="Telangana")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# Uttar_Pradesh

```{r}
state_all <- ec %>% filter(state1=="Uttar_Pradesh")

grant_state <- grant_ec %>% filter(state1=="Uttar_Pradesh")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```


# West_Bengal

```{r}
state_all <- ec %>% filter(state1=="West_Bengal")

grant_state <- grant_ec %>% filter(state1=="West_Bengal")
```

```{r}

library(ggthemes)

density_all_submitted <- ggplot(filter(state_all,submit_year<2024), aes(x = submit_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('Projects Submitted') + theme_economist()

print(density_all_submitted)

```

```{r}

library(ggthemes)

density_all_granted <- ggplot(filter(grant_state,grant_year<2024), aes(x = grant_year)) +
  geom_bar(fill = "skyblue", color = "darkblue", alpha = 0.5) +
    ggtitle('ECs Granted') + theme_economist()

print(density_all_granted)
```

```{r}
set <- state_all %>% filter(year==2016)

ab <- grant_state %>% filter(year!= 2016)
ab2 <- grant_state %>% filter(year== 2016)


#write.csv(set,paste0("C:/Users/",user,"/Desktop/guj.csv"))
```

