---
title: "Odisha EC Analysis"
author: "Anutubh Agnihotri and Pranav Gupta"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```


```{r}
library(sf)
library(tidyverse)
library(cowplot)
library(patchwork)
library(lfe)
library(expss)
library(lubridate)
library(zoo)
```

```{r}
#user <- "agnihotri"
user <- "prana"
```

#Loading Old File

```{r}
or_old <- read.csv("C:/Users/prana/Dropbox/agnihotri_gupta/Environment_Clearance/Final/Orissa_ec_additional_data.csv")

main <- read.csv("C:/Users/prana/Dropbox/agnihotri_gupta/Environment_Clearance/Final/Orissa_ec_additional_data.csv")

time <- read.csv("C:/Users/prana/Dropbox/agnihotri_gupta/Environment_Clearance/Orissa/Backups/merged_timelinedata.csv")

form2 <- read.csv("C:/Users/prana/Dropbox/agnihotri_gupta/Environment_Clearance/Orissa/Backups/merged_form2data.csv")
```

```{r}

grant_ec <- ec %>% filter(Status %in% c("EC Granted","EC Granted - Processed offline")) %>% distinct()
```

```{r}
grant_ec <- ec %>% filter(Status %in% c("EC Granted","EC Granted - Processed offline")) %>% distinct()
```

```{r}
grant_ec$duplicate <- duplicated(grant_ec$Proposal)
table(grant_ec$duplicate)
```
##Simplify the Categories of Projects 

```{r}
grant_ec$Category_Simplified <- ifelse(grepl('INFRA',grant_ec$Category),'Infrastructure',
                                    ifelse(grepl('Industrial',grant_ec$Category),'Industrial',
                                    ifelse(grant_ec$Category=='Non-Coal Mining','Non-Coal Mining','Other')))

table(grant_ec$Category_Simplified)

```

```{r}
extract_after_colon <- function(input) {
  split_string <- strsplit(input, ":")
  extracted_text <- sapply(split_string, function(x) trimws(x[2]))
  return(extracted_text)
}

# Applying the function to the input vector
grant_ec$submit <- extract_after_colon(grant_ec$Date_1) %>% dmy()
grant_ec$grant <- extract_after_colon(grant_ec$Date_2) %>% dmy()

#Time taken to Grant 
grant_ec$time <- as.duration(grant_ec$grant - grant_ec$submit)/ddays(1)
```


```{r}
summary(grant_ec$time)

#Exclude if length  less than 0

grant_ec <- grant_ec %>% filter(time >=0) #Some obs have negative grant time
```

```{r extract-year}
#Year of Submission
#grant_ec$submit_year<-(gsub('^([0-9][0-9][0-9][0-9]).*','\\1',grant_ec$submit))
grant_ec$submit_year <- year(grant_ec$submit)

#Year-Month of Submission
grant_ec$submit_year_mon<-as.yearmon(grant_ec$submit)
```

```{r}
code <- read.csv(paste0("C:/Users/",user,"/Dropbox/agnihotri_gupta/Environment_Clearance/district_lgd.csv")) 
grant_ec <- left_join(grant_ec,code,by="District")
```

```{r}
dist <- grant_ec %>% group_by(census2011,state1) %>% summarise(avg = mean(time),sd = sd(time), count = n(),most = names(table(Category))[which.max(table(Category))])
dist$cd <- dist$sd/dist$avg
dist$census2011 <- sprintf("%03d", dist$census2011)
dist$census2011 <- as.character(dist$census2011)
```

```{r}

```







